// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXaZCrUnHz4QD3lgcQBo9p43ZRXoy2d4',
    appId: '1:777795780886:web:42a21ecbf04000e8041037',
    messagingSenderId: '777795780886',
    projectId: 'mycourse-app-c349b',
    authDomain: 'mycourse-app-c349b.firebaseapp.com',
    storageBucket: 'mycourse-app-c349b.firebasestorage.app',
    measurementId: 'G-JD6W7MSJVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDibygt6yxfYCbvtkhVY69l7V-Lmgfn3pA',
    appId: '1:777795780886:android:032fd57c7d749ac0041037',
    messagingSenderId: '777795780886',
    projectId: 'mycourse-app-c349b',
    storageBucket: 'mycourse-app-c349b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUuyQZvjjqRzbpqZ2n4r1tWclUsAAJO4',
    appId: '1:777795780886:ios:45f232b36862fecc041037',
    messagingSenderId: '777795780886',
    projectId: 'mycourse-app-c349b',
    storageBucket: 'mycourse-app-c349b.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUuyQZvjjqRzbpqZ2n4r1tWclUsAAJO4',
    appId: '1:777795780886:ios:45f232b36862fecc041037',
    messagingSenderId: '777795780886',
    projectId: 'mycourse-app-c349b',
    storageBucket: 'mycourse-app-c349b.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoXaZCrUnHz4QD3lgcQBo9p43ZRXoy2d4',
    appId: '1:777795780886:web:3d1cab9d492b1599041037',
    messagingSenderId: '777795780886',
    projectId: 'mycourse-app-c349b',
    authDomain: 'mycourse-app-c349b.firebaseapp.com',
    storageBucket: 'mycourse-app-c349b.firebasestorage.app',
    measurementId: 'G-5ERH74D4LV',
  );

}